server:
  port: 8084
spring:
  datasource:
    name: gzb
    url: jdbc:mysql://localhost:3306/spring_boot_test?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'X'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1
    port: 6379 # 连接超时时间 单位 ms（毫秒）
    timeout: 5000ms  # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时
    jedis:
      pool: #=========redis线程池设置=========
        max-idle: 20  # 连接池中的最大空闲连接，默认值也是8。
        min-idle: 10   #连接池中的最小空闲连接，默认值也是0。
        max-active: 2000
        max-wait: 1000ms
    database: 2
  application:
    name: gzb

## 该配置节点为独立的节点，将这个配置放在spring的节点下，会导致配置无法被识别
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/**.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ttl.myspringboot.po   # 注意：对应实体类的路径


#pagehelper分页插件
pagehelper:
#  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

logging:
  file: log/myspringboot.log
#  config: classpath:logback/logging-config.xml
  level:
    root: INFO
    com.ttl.myspringboot.dao: DEBUG
    #后面的路径指的是mybatis对应的方法接口所在的包。并不是mapper.xml所在的包。

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer0:8060/eureka/,http://peer1:8061/eureka/,http://peer2:8062/eureka/
    fetch-registry: true
    register-with-eureka: true
