package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_project;
import com.ttl.myspringboot.po.gzb01_t_projectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_projectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_projectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_projectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    int insert(gzb01_t_project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    List<gzb01_t_project> selectByExample(gzb01_t_projectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    gzb01_t_project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_project record, @Param("example") gzb01_t_projectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_project record, @Param("example") gzb01_t_projectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_project record);
}