package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_project_group;
import com.ttl.myspringboot.po.gzb01_t_project_groupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_project_groupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_project_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_project_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    int insert(gzb01_t_project_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_project_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    List<gzb01_t_project_group> selectByExample(gzb01_t_project_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    gzb01_t_project_group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_project_group record, @Param("example") gzb01_t_project_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_project_group record, @Param("example") gzb01_t_project_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_project_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_project_group record);
}