package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_user_sign_record;
import com.ttl.myspringboot.po.gzb01_t_user_sign_recordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_user_sign_recordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_user_sign_recordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_user_sign_recordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    int insert(gzb01_t_user_sign_record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_user_sign_record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    List<gzb01_t_user_sign_record> selectByExample(gzb01_t_user_sign_recordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    gzb01_t_user_sign_record selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_user_sign_record record, @Param("example") gzb01_t_user_sign_recordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_user_sign_record record, @Param("example") gzb01_t_user_sign_recordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_user_sign_record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_sign_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_user_sign_record record);
}