package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_message;
import com.ttl.myspringboot.po.gzb01_t_messageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_messageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int insert(gzb01_t_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    List<gzb01_t_message> selectByExampleWithBLOBs(gzb01_t_messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    List<gzb01_t_message> selectByExample(gzb01_t_messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    gzb01_t_message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_message record, @Param("example") gzb01_t_messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") gzb01_t_message record, @Param("example") gzb01_t_messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_message record, @Param("example") gzb01_t_messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(gzb01_t_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_message record);
}