package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_project_member;
import com.ttl.myspringboot.po.gzb01_t_project_memberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_project_memberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    int insert(gzb01_t_project_member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_project_member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    List<gzb01_t_project_member> selectByExample(gzb01_t_project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    gzb01_t_project_member selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_project_member record, @Param("example") gzb01_t_project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_project_member record, @Param("example") gzb01_t_project_memberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_project_member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_project_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_project_member record);
}