package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_phone_info;
import com.ttl.myspringboot.po.gzb01_t_phone_infoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_phone_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_phone_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_phone_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    int insert(gzb01_t_phone_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_phone_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    List<gzb01_t_phone_info> selectByExample(gzb01_t_phone_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    gzb01_t_phone_info selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_phone_info record, @Param("example") gzb01_t_phone_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_phone_info record, @Param("example") gzb01_t_phone_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_phone_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_phone_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_phone_info record);
}