package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_user;
import com.ttl.myspringboot.po.gzb01_t_userExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    int insert(gzb01_t_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    List<gzb01_t_user> selectByExample(gzb01_t_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    gzb01_t_user selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_user record, @Param("example") gzb01_t_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_user record, @Param("example") gzb01_t_userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_user record);
}