package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_sum_role;
import com.ttl.myspringboot.po.gzb01_t_sum_roleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_sum_roleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sum_role
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_sum_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sum_role
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_sum_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sum_role
     *
     * @mbggenerated
     */
    int insert(gzb01_t_sum_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sum_role
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_sum_role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sum_role
     *
     * @mbggenerated
     */
    List<gzb01_t_sum_role> selectByExample(gzb01_t_sum_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sum_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_sum_role record, @Param("example") gzb01_t_sum_roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sum_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_sum_role record, @Param("example") gzb01_t_sum_roleExample example);
}