package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_sign_strategy;
import com.ttl.myspringboot.po.gzb01_t_sign_strategyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_sign_strategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_sign_strategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_sign_strategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    int insert(gzb01_t_sign_strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_sign_strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    List<gzb01_t_sign_strategy> selectByExample(gzb01_t_sign_strategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    gzb01_t_sign_strategy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_sign_strategy record, @Param("example") gzb01_t_sign_strategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_sign_strategy record, @Param("example") gzb01_t_sign_strategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_sign_strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_sign_strategy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_sign_strategy record);
}