package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_user_lack_attendance;
import com.ttl.myspringboot.po.gzb01_t_user_lack_attendanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_user_lack_attendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_user_lack_attendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_user_lack_attendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    int insert(gzb01_t_user_lack_attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_user_lack_attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    List<gzb01_t_user_lack_attendance> selectByExample(gzb01_t_user_lack_attendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    gzb01_t_user_lack_attendance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_user_lack_attendance record, @Param("example") gzb01_t_user_lack_attendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_user_lack_attendance record, @Param("example") gzb01_t_user_lack_attendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_user_lack_attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_user_lack_attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_user_lack_attendance record);
}