package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.gzb01_t_location_favorite;
import com.ttl.myspringboot.po.gzb01_t_location_favoriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface gzb01_t_location_favoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    int countByExample(gzb01_t_location_favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    int deleteByExample(gzb01_t_location_favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    int insert(gzb01_t_location_favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    int insertSelective(gzb01_t_location_favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    List<gzb01_t_location_favorite> selectByExample(gzb01_t_location_favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    gzb01_t_location_favorite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") gzb01_t_location_favorite record, @Param("example") gzb01_t_location_favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") gzb01_t_location_favorite record, @Param("example") gzb01_t_location_favoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(gzb01_t_location_favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gzb01_t_location_favorite
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(gzb01_t_location_favorite record);
}