package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_calendars;
import com.ttl.myspringboot.po.qrtz_calendarsExample;
import com.ttl.myspringboot.po.qrtz_calendarsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_calendarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int countByExample(qrtz_calendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_calendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_calendarsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int insert(qrtz_calendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_calendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    List<qrtz_calendars> selectByExampleWithBLOBs(qrtz_calendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    List<qrtz_calendars> selectByExample(qrtz_calendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    qrtz_calendars selectByPrimaryKey(qrtz_calendarsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_calendars record, @Param("example") qrtz_calendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") qrtz_calendars record, @Param("example") qrtz_calendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_calendars record, @Param("example") qrtz_calendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(qrtz_calendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(qrtz_calendars record);
}