package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_scheduler_state;
import com.ttl.myspringboot.po.qrtz_scheduler_stateExample;
import com.ttl.myspringboot.po.qrtz_scheduler_stateKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_scheduler_stateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int countByExample(qrtz_scheduler_stateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_scheduler_stateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_scheduler_stateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int insert(qrtz_scheduler_state record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_scheduler_state record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    List<qrtz_scheduler_state> selectByExample(qrtz_scheduler_stateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    qrtz_scheduler_state selectByPrimaryKey(qrtz_scheduler_stateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_scheduler_state record, @Param("example") qrtz_scheduler_stateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_scheduler_state record, @Param("example") qrtz_scheduler_stateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(qrtz_scheduler_state record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(qrtz_scheduler_state record);
}