package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_blob_triggers;
import com.ttl.myspringboot.po.qrtz_blob_triggersExample;
import com.ttl.myspringboot.po.qrtz_blob_triggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_blob_triggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int countByExample(qrtz_blob_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_blob_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_blob_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int insert(qrtz_blob_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_blob_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    List<qrtz_blob_triggers> selectByExampleWithBLOBs(qrtz_blob_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    List<qrtz_blob_triggers> selectByExample(qrtz_blob_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    qrtz_blob_triggers selectByPrimaryKey(qrtz_blob_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_blob_triggers record, @Param("example") qrtz_blob_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") qrtz_blob_triggers record, @Param("example") qrtz_blob_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_blob_triggers record, @Param("example") qrtz_blob_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(qrtz_blob_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(qrtz_blob_triggers record);
}