package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_simprop_triggers;
import com.ttl.myspringboot.po.qrtz_simprop_triggersExample;
import com.ttl.myspringboot.po.qrtz_simprop_triggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_simprop_triggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int countByExample(qrtz_simprop_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_simprop_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_simprop_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int insert(qrtz_simprop_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_simprop_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    List<qrtz_simprop_triggers> selectByExample(qrtz_simprop_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    qrtz_simprop_triggers selectByPrimaryKey(qrtz_simprop_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_simprop_triggers record, @Param("example") qrtz_simprop_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_simprop_triggers record, @Param("example") qrtz_simprop_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(qrtz_simprop_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(qrtz_simprop_triggers record);
}