package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_triggers;
import com.ttl.myspringboot.po.qrtz_triggersExample;
import com.ttl.myspringboot.po.qrtz_triggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_triggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int countByExample(qrtz_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int insert(qrtz_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    List<qrtz_triggers> selectByExampleWithBLOBs(qrtz_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    List<qrtz_triggers> selectByExample(qrtz_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    qrtz_triggers selectByPrimaryKey(qrtz_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_triggers record, @Param("example") qrtz_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") qrtz_triggers record, @Param("example") qrtz_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_triggers record, @Param("example") qrtz_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(qrtz_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(qrtz_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(qrtz_triggers record);
}