package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_cron_triggers;
import com.ttl.myspringboot.po.qrtz_cron_triggersExample;
import com.ttl.myspringboot.po.qrtz_cron_triggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_cron_triggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    int countByExample(qrtz_cron_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_cron_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_cron_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    int insert(qrtz_cron_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_cron_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    List<qrtz_cron_triggers> selectByExample(qrtz_cron_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    qrtz_cron_triggers selectByPrimaryKey(qrtz_cron_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_cron_triggers record, @Param("example") qrtz_cron_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_cron_triggers record, @Param("example") qrtz_cron_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(qrtz_cron_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(qrtz_cron_triggers record);
}