package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_paused_trigger_grpsExample;
import com.ttl.myspringboot.po.qrtz_paused_trigger_grpsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_paused_trigger_grpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated
     */
    int countByExample(qrtz_paused_trigger_grpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_paused_trigger_grpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_paused_trigger_grpsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated
     */
    int insert(qrtz_paused_trigger_grpsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_paused_trigger_grpsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated
     */
    List<qrtz_paused_trigger_grpsKey> selectByExample(qrtz_paused_trigger_grpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_paused_trigger_grpsKey record, @Param("example") qrtz_paused_trigger_grpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_paused_trigger_grpsKey record, @Param("example") qrtz_paused_trigger_grpsExample example);
}