package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_job_details;
import com.ttl.myspringboot.po.qrtz_job_detailsExample;
import com.ttl.myspringboot.po.qrtz_job_detailsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_job_detailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int countByExample(qrtz_job_detailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_job_detailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_job_detailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int insert(qrtz_job_details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_job_details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    List<qrtz_job_details> selectByExampleWithBLOBs(qrtz_job_detailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    List<qrtz_job_details> selectByExample(qrtz_job_detailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    qrtz_job_details selectByPrimaryKey(qrtz_job_detailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_job_details record, @Param("example") qrtz_job_detailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") qrtz_job_details record, @Param("example") qrtz_job_detailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_job_details record, @Param("example") qrtz_job_detailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(qrtz_job_details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(qrtz_job_details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(qrtz_job_details record);
}