package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_fired_triggers;
import com.ttl.myspringboot.po.qrtz_fired_triggersExample;
import com.ttl.myspringboot.po.qrtz_fired_triggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_fired_triggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    int countByExample(qrtz_fired_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_fired_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_fired_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    int insert(qrtz_fired_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_fired_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    List<qrtz_fired_triggers> selectByExample(qrtz_fired_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    qrtz_fired_triggers selectByPrimaryKey(qrtz_fired_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_fired_triggers record, @Param("example") qrtz_fired_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_fired_triggers record, @Param("example") qrtz_fired_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(qrtz_fired_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(qrtz_fired_triggers record);
}