package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_locksExample;
import com.ttl.myspringboot.po.qrtz_locksKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_locksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    int countByExample(qrtz_locksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_locksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_locksKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    int insert(qrtz_locksKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_locksKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    List<qrtz_locksKey> selectByExample(qrtz_locksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_locksKey record, @Param("example") qrtz_locksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_locksKey record, @Param("example") qrtz_locksExample example);
}