package com.ttl.myspringboot.dao;

import com.ttl.myspringboot.po.qrtz_simple_triggers;
import com.ttl.myspringboot.po.qrtz_simple_triggersExample;
import com.ttl.myspringboot.po.qrtz_simple_triggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface qrtz_simple_triggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    int countByExample(qrtz_simple_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    int deleteByExample(qrtz_simple_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(qrtz_simple_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    int insert(qrtz_simple_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    int insertSelective(qrtz_simple_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    List<qrtz_simple_triggers> selectByExample(qrtz_simple_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    qrtz_simple_triggers selectByPrimaryKey(qrtz_simple_triggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") qrtz_simple_triggers record, @Param("example") qrtz_simple_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") qrtz_simple_triggers record, @Param("example") qrtz_simple_triggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(qrtz_simple_triggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(qrtz_simple_triggers record);
}