package com.ttl.myspringboot.po;

public class gzb01_t_indusry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_indusry.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_indusry.industry_name
     *
     * @mbggenerated
     */
    private String industryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_indusry.industry_status
     *
     * @mbggenerated
     */
    private Byte industryStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_indusry.id
     *
     * @return the value of gzb01_t_indusry.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_indusry.id
     *
     * @param id the value for gzb01_t_indusry.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_indusry.industry_name
     *
     * @return the value of gzb01_t_indusry.industry_name
     *
     * @mbggenerated
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_indusry.industry_name
     *
     * @param industryName the value for gzb01_t_indusry.industry_name
     *
     * @mbggenerated
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_indusry.industry_status
     *
     * @return the value of gzb01_t_indusry.industry_status
     *
     * @mbggenerated
     */
    public Byte getIndustryStatus() {
        return industryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_indusry.industry_status
     *
     * @param industryStatus the value for gzb01_t_indusry.industry_status
     *
     * @mbggenerated
     */
    public void setIndustryStatus(Byte industryStatus) {
        this.industryStatus = industryStatus;
    }
}