package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_user_sign_strategy_template {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_strategy_template.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_strategy_template.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_strategy_template.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_strategy_template.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_strategy_template.strategy_id
     *
     * @mbggenerated
     */
    private Integer strategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_strategy_template.sign_date
     *
     * @mbggenerated
     */
    private Date signDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_strategy_template.is_available
     *
     * @mbggenerated
     */
    private Byte isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_strategy_template.id
     *
     * @return the value of gzb01_t_user_sign_strategy_template.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_strategy_template.id
     *
     * @param id the value for gzb01_t_user_sign_strategy_template.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_strategy_template.user_id
     *
     * @return the value of gzb01_t_user_sign_strategy_template.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_strategy_template.user_id
     *
     * @param userId the value for gzb01_t_user_sign_strategy_template.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_strategy_template.group_id
     *
     * @return the value of gzb01_t_user_sign_strategy_template.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_strategy_template.group_id
     *
     * @param groupId the value for gzb01_t_user_sign_strategy_template.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_strategy_template.project_id
     *
     * @return the value of gzb01_t_user_sign_strategy_template.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_strategy_template.project_id
     *
     * @param projectId the value for gzb01_t_user_sign_strategy_template.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_strategy_template.strategy_id
     *
     * @return the value of gzb01_t_user_sign_strategy_template.strategy_id
     *
     * @mbggenerated
     */
    public Integer getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_strategy_template.strategy_id
     *
     * @param strategyId the value for gzb01_t_user_sign_strategy_template.strategy_id
     *
     * @mbggenerated
     */
    public void setStrategyId(Integer strategyId) {
        this.strategyId = strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_strategy_template.sign_date
     *
     * @return the value of gzb01_t_user_sign_strategy_template.sign_date
     *
     * @mbggenerated
     */
    public Date getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_strategy_template.sign_date
     *
     * @param signDate the value for gzb01_t_user_sign_strategy_template.sign_date
     *
     * @mbggenerated
     */
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_strategy_template.is_available
     *
     * @return the value of gzb01_t_user_sign_strategy_template.is_available
     *
     * @mbggenerated
     */
    public Byte getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_strategy_template.is_available
     *
     * @param isAvailable the value for gzb01_t_user_sign_strategy_template.is_available
     *
     * @mbggenerated
     */
    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }
}