package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_news {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.subtitle
     *
     * @mbggenerated
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.nav_type
     *
     * @mbggenerated
     */
    private Byte navType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.second_type
     *
     * @mbggenerated
     */
    private Byte secondType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.is_img
     *
     * @mbggenerated
     */
    private Byte isImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.pic_url
     *
     * @mbggenerated
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.vocation_id
     *
     * @mbggenerated
     */
    private Integer vocationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.district _id
     *
     * @mbggenerated
     */
    private Integer districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.new_from
     *
     * @mbggenerated
     */
    private String newFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_news.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.id
     *
     * @return the value of gzb01_t_news.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.id
     *
     * @param id the value for gzb01_t_news.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.title
     *
     * @return the value of gzb01_t_news.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.title
     *
     * @param title the value for gzb01_t_news.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.subtitle
     *
     * @return the value of gzb01_t_news.subtitle
     *
     * @mbggenerated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.subtitle
     *
     * @param subtitle the value for gzb01_t_news.subtitle
     *
     * @mbggenerated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.create_time
     *
     * @return the value of gzb01_t_news.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.create_time
     *
     * @param createTime the value for gzb01_t_news.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.nav_type
     *
     * @return the value of gzb01_t_news.nav_type
     *
     * @mbggenerated
     */
    public Byte getNavType() {
        return navType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.nav_type
     *
     * @param navType the value for gzb01_t_news.nav_type
     *
     * @mbggenerated
     */
    public void setNavType(Byte navType) {
        this.navType = navType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.second_type
     *
     * @return the value of gzb01_t_news.second_type
     *
     * @mbggenerated
     */
    public Byte getSecondType() {
        return secondType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.second_type
     *
     * @param secondType the value for gzb01_t_news.second_type
     *
     * @mbggenerated
     */
    public void setSecondType(Byte secondType) {
        this.secondType = secondType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.is_img
     *
     * @return the value of gzb01_t_news.is_img
     *
     * @mbggenerated
     */
    public Byte getIsImg() {
        return isImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.is_img
     *
     * @param isImg the value for gzb01_t_news.is_img
     *
     * @mbggenerated
     */
    public void setIsImg(Byte isImg) {
        this.isImg = isImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.pic_url
     *
     * @return the value of gzb01_t_news.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.pic_url
     *
     * @param picUrl the value for gzb01_t_news.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.vocation_id
     *
     * @return the value of gzb01_t_news.vocation_id
     *
     * @mbggenerated
     */
    public Integer getVocationId() {
        return vocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.vocation_id
     *
     * @param vocationId the value for gzb01_t_news.vocation_id
     *
     * @mbggenerated
     */
    public void setVocationId(Integer vocationId) {
        this.vocationId = vocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.district _id
     *
     * @return the value of gzb01_t_news.district _id
     *
     * @mbggenerated
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.district _id
     *
     * @param districtId the value for gzb01_t_news.district _id
     *
     * @mbggenerated
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.new_from
     *
     * @return the value of gzb01_t_news.new_from
     *
     * @mbggenerated
     */
    public String getNewFrom() {
        return newFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.new_from
     *
     * @param newFrom the value for gzb01_t_news.new_from
     *
     * @mbggenerated
     */
    public void setNewFrom(String newFrom) {
        this.newFrom = newFrom == null ? null : newFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_news.content
     *
     * @return the value of gzb01_t_news.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_news.content
     *
     * @param content the value for gzb01_t_news.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}