package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_user_check {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_check.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_check.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_check.file_url
     *
     * @mbggenerated
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_check.apply_time
     *
     * @mbggenerated
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_check.before_role_id
     *
     * @mbggenerated
     */
    private Integer beforeRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_check.after_role_id
     *
     * @mbggenerated
     */
    private Integer afterRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_check.check_time
     *
     * @mbggenerated
     */
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_check.check_status
     *
     * @mbggenerated
     */
    private Byte checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_check.check_result
     *
     * @mbggenerated
     */
    private Byte checkResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_check.id
     *
     * @return the value of gzb01_t_user_check.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_check.id
     *
     * @param id the value for gzb01_t_user_check.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_check.user_id
     *
     * @return the value of gzb01_t_user_check.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_check.user_id
     *
     * @param userId the value for gzb01_t_user_check.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_check.file_url
     *
     * @return the value of gzb01_t_user_check.file_url
     *
     * @mbggenerated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_check.file_url
     *
     * @param fileUrl the value for gzb01_t_user_check.file_url
     *
     * @mbggenerated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_check.apply_time
     *
     * @return the value of gzb01_t_user_check.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_check.apply_time
     *
     * @param applyTime the value for gzb01_t_user_check.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_check.before_role_id
     *
     * @return the value of gzb01_t_user_check.before_role_id
     *
     * @mbggenerated
     */
    public Integer getBeforeRoleId() {
        return beforeRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_check.before_role_id
     *
     * @param beforeRoleId the value for gzb01_t_user_check.before_role_id
     *
     * @mbggenerated
     */
    public void setBeforeRoleId(Integer beforeRoleId) {
        this.beforeRoleId = beforeRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_check.after_role_id
     *
     * @return the value of gzb01_t_user_check.after_role_id
     *
     * @mbggenerated
     */
    public Integer getAfterRoleId() {
        return afterRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_check.after_role_id
     *
     * @param afterRoleId the value for gzb01_t_user_check.after_role_id
     *
     * @mbggenerated
     */
    public void setAfterRoleId(Integer afterRoleId) {
        this.afterRoleId = afterRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_check.check_time
     *
     * @return the value of gzb01_t_user_check.check_time
     *
     * @mbggenerated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_check.check_time
     *
     * @param checkTime the value for gzb01_t_user_check.check_time
     *
     * @mbggenerated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_check.check_status
     *
     * @return the value of gzb01_t_user_check.check_status
     *
     * @mbggenerated
     */
    public Byte getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_check.check_status
     *
     * @param checkStatus the value for gzb01_t_user_check.check_status
     *
     * @mbggenerated
     */
    public void setCheckStatus(Byte checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_check.check_result
     *
     * @return the value of gzb01_t_user_check.check_result
     *
     * @mbggenerated
     */
    public Byte getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_check.check_result
     *
     * @param checkResult the value for gzb01_t_user_check.check_result
     *
     * @mbggenerated
     */
    public void setCheckResult(Byte checkResult) {
        this.checkResult = checkResult;
    }
}