package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_time_rule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.time_name
     *
     * @mbggenerated
     */
    private String timeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.time_desc
     *
     * @mbggenerated
     */
    private String timeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_in_time1
     *
     * @mbggenerated
     */
    private Date signInTime1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_in_before1
     *
     * @mbggenerated
     */
    private Integer signInBefore1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_in_after1
     *
     * @mbggenerated
     */
    private Integer signInAfter1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_out_time1
     *
     * @mbggenerated
     */
    private Date signOutTime1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_out_before1
     *
     * @mbggenerated
     */
    private Integer signOutBefore1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_out_after1
     *
     * @mbggenerated
     */
    private Integer signOutAfter1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_in_time2
     *
     * @mbggenerated
     */
    private Date signInTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_in_before2
     *
     * @mbggenerated
     */
    private Integer signInBefore2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_in_after2
     *
     * @mbggenerated
     */
    private Integer signInAfter2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_out_time2
     *
     * @mbggenerated
     */
    private Date signOutTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_out_before2
     *
     * @mbggenerated
     */
    private Integer signOutBefore2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.sign_out_after2
     *
     * @mbggenerated
     */
    private Integer signOutAfter2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.time_rule_type
     *
     * @mbggenerated
     */
    private Byte timeRuleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_time_rule.is_available
     *
     * @mbggenerated
     */
    private Byte isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.id
     *
     * @return the value of gzb01_t_time_rule.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.id
     *
     * @param id the value for gzb01_t_time_rule.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.time_name
     *
     * @return the value of gzb01_t_time_rule.time_name
     *
     * @mbggenerated
     */
    public String getTimeName() {
        return timeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.time_name
     *
     * @param timeName the value for gzb01_t_time_rule.time_name
     *
     * @mbggenerated
     */
    public void setTimeName(String timeName) {
        this.timeName = timeName == null ? null : timeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.time_desc
     *
     * @return the value of gzb01_t_time_rule.time_desc
     *
     * @mbggenerated
     */
    public String getTimeDesc() {
        return timeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.time_desc
     *
     * @param timeDesc the value for gzb01_t_time_rule.time_desc
     *
     * @mbggenerated
     */
    public void setTimeDesc(String timeDesc) {
        this.timeDesc = timeDesc == null ? null : timeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_in_time1
     *
     * @return the value of gzb01_t_time_rule.sign_in_time1
     *
     * @mbggenerated
     */
    public Date getSignInTime1() {
        return signInTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_in_time1
     *
     * @param signInTime1 the value for gzb01_t_time_rule.sign_in_time1
     *
     * @mbggenerated
     */
    public void setSignInTime1(Date signInTime1) {
        this.signInTime1 = signInTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_in_before1
     *
     * @return the value of gzb01_t_time_rule.sign_in_before1
     *
     * @mbggenerated
     */
    public Integer getSignInBefore1() {
        return signInBefore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_in_before1
     *
     * @param signInBefore1 the value for gzb01_t_time_rule.sign_in_before1
     *
     * @mbggenerated
     */
    public void setSignInBefore1(Integer signInBefore1) {
        this.signInBefore1 = signInBefore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_in_after1
     *
     * @return the value of gzb01_t_time_rule.sign_in_after1
     *
     * @mbggenerated
     */
    public Integer getSignInAfter1() {
        return signInAfter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_in_after1
     *
     * @param signInAfter1 the value for gzb01_t_time_rule.sign_in_after1
     *
     * @mbggenerated
     */
    public void setSignInAfter1(Integer signInAfter1) {
        this.signInAfter1 = signInAfter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_out_time1
     *
     * @return the value of gzb01_t_time_rule.sign_out_time1
     *
     * @mbggenerated
     */
    public Date getSignOutTime1() {
        return signOutTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_out_time1
     *
     * @param signOutTime1 the value for gzb01_t_time_rule.sign_out_time1
     *
     * @mbggenerated
     */
    public void setSignOutTime1(Date signOutTime1) {
        this.signOutTime1 = signOutTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_out_before1
     *
     * @return the value of gzb01_t_time_rule.sign_out_before1
     *
     * @mbggenerated
     */
    public Integer getSignOutBefore1() {
        return signOutBefore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_out_before1
     *
     * @param signOutBefore1 the value for gzb01_t_time_rule.sign_out_before1
     *
     * @mbggenerated
     */
    public void setSignOutBefore1(Integer signOutBefore1) {
        this.signOutBefore1 = signOutBefore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_out_after1
     *
     * @return the value of gzb01_t_time_rule.sign_out_after1
     *
     * @mbggenerated
     */
    public Integer getSignOutAfter1() {
        return signOutAfter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_out_after1
     *
     * @param signOutAfter1 the value for gzb01_t_time_rule.sign_out_after1
     *
     * @mbggenerated
     */
    public void setSignOutAfter1(Integer signOutAfter1) {
        this.signOutAfter1 = signOutAfter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_in_time2
     *
     * @return the value of gzb01_t_time_rule.sign_in_time2
     *
     * @mbggenerated
     */
    public Date getSignInTime2() {
        return signInTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_in_time2
     *
     * @param signInTime2 the value for gzb01_t_time_rule.sign_in_time2
     *
     * @mbggenerated
     */
    public void setSignInTime2(Date signInTime2) {
        this.signInTime2 = signInTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_in_before2
     *
     * @return the value of gzb01_t_time_rule.sign_in_before2
     *
     * @mbggenerated
     */
    public Integer getSignInBefore2() {
        return signInBefore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_in_before2
     *
     * @param signInBefore2 the value for gzb01_t_time_rule.sign_in_before2
     *
     * @mbggenerated
     */
    public void setSignInBefore2(Integer signInBefore2) {
        this.signInBefore2 = signInBefore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_in_after2
     *
     * @return the value of gzb01_t_time_rule.sign_in_after2
     *
     * @mbggenerated
     */
    public Integer getSignInAfter2() {
        return signInAfter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_in_after2
     *
     * @param signInAfter2 the value for gzb01_t_time_rule.sign_in_after2
     *
     * @mbggenerated
     */
    public void setSignInAfter2(Integer signInAfter2) {
        this.signInAfter2 = signInAfter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_out_time2
     *
     * @return the value of gzb01_t_time_rule.sign_out_time2
     *
     * @mbggenerated
     */
    public Date getSignOutTime2() {
        return signOutTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_out_time2
     *
     * @param signOutTime2 the value for gzb01_t_time_rule.sign_out_time2
     *
     * @mbggenerated
     */
    public void setSignOutTime2(Date signOutTime2) {
        this.signOutTime2 = signOutTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_out_before2
     *
     * @return the value of gzb01_t_time_rule.sign_out_before2
     *
     * @mbggenerated
     */
    public Integer getSignOutBefore2() {
        return signOutBefore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_out_before2
     *
     * @param signOutBefore2 the value for gzb01_t_time_rule.sign_out_before2
     *
     * @mbggenerated
     */
    public void setSignOutBefore2(Integer signOutBefore2) {
        this.signOutBefore2 = signOutBefore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.sign_out_after2
     *
     * @return the value of gzb01_t_time_rule.sign_out_after2
     *
     * @mbggenerated
     */
    public Integer getSignOutAfter2() {
        return signOutAfter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.sign_out_after2
     *
     * @param signOutAfter2 the value for gzb01_t_time_rule.sign_out_after2
     *
     * @mbggenerated
     */
    public void setSignOutAfter2(Integer signOutAfter2) {
        this.signOutAfter2 = signOutAfter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.time_rule_type
     *
     * @return the value of gzb01_t_time_rule.time_rule_type
     *
     * @mbggenerated
     */
    public Byte getTimeRuleType() {
        return timeRuleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.time_rule_type
     *
     * @param timeRuleType the value for gzb01_t_time_rule.time_rule_type
     *
     * @mbggenerated
     */
    public void setTimeRuleType(Byte timeRuleType) {
        this.timeRuleType = timeRuleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_time_rule.is_available
     *
     * @return the value of gzb01_t_time_rule.is_available
     *
     * @mbggenerated
     */
    public Byte getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_time_rule.is_available
     *
     * @param isAvailable the value for gzb01_t_time_rule.is_available
     *
     * @mbggenerated
     */
    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }
}