package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_user_sign_record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_date
     *
     * @mbggenerated
     */
    private Date signDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_time1
     *
     * @mbggenerated
     */
    private Date signInTime1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_time1
     *
     * @mbggenerated
     */
    private Date signOutTime1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_add1
     *
     * @mbggenerated
     */
    private String signInAdd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_lat1
     *
     * @mbggenerated
     */
    private String signInLat1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_lng1
     *
     * @mbggenerated
     */
    private String signInLng1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_add1
     *
     * @mbggenerated
     */
    private String signOutAdd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_lat1
     *
     * @mbggenerated
     */
    private String signOutLat1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_lng1
     *
     * @mbggenerated
     */
    private String signOutLng1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_time2
     *
     * @mbggenerated
     */
    private Date signInTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_time2
     *
     * @mbggenerated
     */
    private Date signOutTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_add2
     *
     * @mbggenerated
     */
    private String signInAdd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_lat2
     *
     * @mbggenerated
     */
    private String signInLat2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_lng2
     *
     * @mbggenerated
     */
    private String signInLng2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_add2
     *
     * @mbggenerated
     */
    private String signOutAdd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_lat2
     *
     * @mbggenerated
     */
    private String signOutLat2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_lng2
     *
     * @mbggenerated
     */
    private String signOutLng2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.strategy_id
     *
     * @mbggenerated
     */
    private Integer strategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_type1
     *
     * @mbggenerated
     */
    private Byte signInType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_type1
     *
     * @mbggenerated
     */
    private Byte signOutType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_in_type2
     *
     * @mbggenerated
     */
    private Byte signInType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.sign_out_type2
     *
     * @mbggenerated
     */
    private Byte signOutType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.full_attendance
     *
     * @mbggenerated
     */
    private Byte fullAttendance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.check_in
     *
     * @mbggenerated
     */
    private Byte checkIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_sign_record.is_available
     *
     * @mbggenerated
     */
    private Byte isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.id
     *
     * @return the value of gzb01_t_user_sign_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.id
     *
     * @param id the value for gzb01_t_user_sign_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.user_id
     *
     * @return the value of gzb01_t_user_sign_record.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.user_id
     *
     * @param userId the value for gzb01_t_user_sign_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.group_id
     *
     * @return the value of gzb01_t_user_sign_record.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.group_id
     *
     * @param groupId the value for gzb01_t_user_sign_record.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.project_id
     *
     * @return the value of gzb01_t_user_sign_record.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.project_id
     *
     * @param projectId the value for gzb01_t_user_sign_record.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_date
     *
     * @return the value of gzb01_t_user_sign_record.sign_date
     *
     * @mbggenerated
     */
    public Date getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_date
     *
     * @param signDate the value for gzb01_t_user_sign_record.sign_date
     *
     * @mbggenerated
     */
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_time1
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_time1
     *
     * @mbggenerated
     */
    public Date getSignInTime1() {
        return signInTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_time1
     *
     * @param signInTime1 the value for gzb01_t_user_sign_record.sign_in_time1
     *
     * @mbggenerated
     */
    public void setSignInTime1(Date signInTime1) {
        this.signInTime1 = signInTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_time1
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_time1
     *
     * @mbggenerated
     */
    public Date getSignOutTime1() {
        return signOutTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_time1
     *
     * @param signOutTime1 the value for gzb01_t_user_sign_record.sign_out_time1
     *
     * @mbggenerated
     */
    public void setSignOutTime1(Date signOutTime1) {
        this.signOutTime1 = signOutTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_add1
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_add1
     *
     * @mbggenerated
     */
    public String getSignInAdd1() {
        return signInAdd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_add1
     *
     * @param signInAdd1 the value for gzb01_t_user_sign_record.sign_in_add1
     *
     * @mbggenerated
     */
    public void setSignInAdd1(String signInAdd1) {
        this.signInAdd1 = signInAdd1 == null ? null : signInAdd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_lat1
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_lat1
     *
     * @mbggenerated
     */
    public String getSignInLat1() {
        return signInLat1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_lat1
     *
     * @param signInLat1 the value for gzb01_t_user_sign_record.sign_in_lat1
     *
     * @mbggenerated
     */
    public void setSignInLat1(String signInLat1) {
        this.signInLat1 = signInLat1 == null ? null : signInLat1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_lng1
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_lng1
     *
     * @mbggenerated
     */
    public String getSignInLng1() {
        return signInLng1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_lng1
     *
     * @param signInLng1 the value for gzb01_t_user_sign_record.sign_in_lng1
     *
     * @mbggenerated
     */
    public void setSignInLng1(String signInLng1) {
        this.signInLng1 = signInLng1 == null ? null : signInLng1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_add1
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_add1
     *
     * @mbggenerated
     */
    public String getSignOutAdd1() {
        return signOutAdd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_add1
     *
     * @param signOutAdd1 the value for gzb01_t_user_sign_record.sign_out_add1
     *
     * @mbggenerated
     */
    public void setSignOutAdd1(String signOutAdd1) {
        this.signOutAdd1 = signOutAdd1 == null ? null : signOutAdd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_lat1
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_lat1
     *
     * @mbggenerated
     */
    public String getSignOutLat1() {
        return signOutLat1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_lat1
     *
     * @param signOutLat1 the value for gzb01_t_user_sign_record.sign_out_lat1
     *
     * @mbggenerated
     */
    public void setSignOutLat1(String signOutLat1) {
        this.signOutLat1 = signOutLat1 == null ? null : signOutLat1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_lng1
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_lng1
     *
     * @mbggenerated
     */
    public String getSignOutLng1() {
        return signOutLng1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_lng1
     *
     * @param signOutLng1 the value for gzb01_t_user_sign_record.sign_out_lng1
     *
     * @mbggenerated
     */
    public void setSignOutLng1(String signOutLng1) {
        this.signOutLng1 = signOutLng1 == null ? null : signOutLng1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_time2
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_time2
     *
     * @mbggenerated
     */
    public Date getSignInTime2() {
        return signInTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_time2
     *
     * @param signInTime2 the value for gzb01_t_user_sign_record.sign_in_time2
     *
     * @mbggenerated
     */
    public void setSignInTime2(Date signInTime2) {
        this.signInTime2 = signInTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_time2
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_time2
     *
     * @mbggenerated
     */
    public Date getSignOutTime2() {
        return signOutTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_time2
     *
     * @param signOutTime2 the value for gzb01_t_user_sign_record.sign_out_time2
     *
     * @mbggenerated
     */
    public void setSignOutTime2(Date signOutTime2) {
        this.signOutTime2 = signOutTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_add2
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_add2
     *
     * @mbggenerated
     */
    public String getSignInAdd2() {
        return signInAdd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_add2
     *
     * @param signInAdd2 the value for gzb01_t_user_sign_record.sign_in_add2
     *
     * @mbggenerated
     */
    public void setSignInAdd2(String signInAdd2) {
        this.signInAdd2 = signInAdd2 == null ? null : signInAdd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_lat2
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_lat2
     *
     * @mbggenerated
     */
    public String getSignInLat2() {
        return signInLat2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_lat2
     *
     * @param signInLat2 the value for gzb01_t_user_sign_record.sign_in_lat2
     *
     * @mbggenerated
     */
    public void setSignInLat2(String signInLat2) {
        this.signInLat2 = signInLat2 == null ? null : signInLat2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_lng2
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_lng2
     *
     * @mbggenerated
     */
    public String getSignInLng2() {
        return signInLng2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_lng2
     *
     * @param signInLng2 the value for gzb01_t_user_sign_record.sign_in_lng2
     *
     * @mbggenerated
     */
    public void setSignInLng2(String signInLng2) {
        this.signInLng2 = signInLng2 == null ? null : signInLng2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_add2
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_add2
     *
     * @mbggenerated
     */
    public String getSignOutAdd2() {
        return signOutAdd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_add2
     *
     * @param signOutAdd2 the value for gzb01_t_user_sign_record.sign_out_add2
     *
     * @mbggenerated
     */
    public void setSignOutAdd2(String signOutAdd2) {
        this.signOutAdd2 = signOutAdd2 == null ? null : signOutAdd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_lat2
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_lat2
     *
     * @mbggenerated
     */
    public String getSignOutLat2() {
        return signOutLat2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_lat2
     *
     * @param signOutLat2 the value for gzb01_t_user_sign_record.sign_out_lat2
     *
     * @mbggenerated
     */
    public void setSignOutLat2(String signOutLat2) {
        this.signOutLat2 = signOutLat2 == null ? null : signOutLat2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_lng2
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_lng2
     *
     * @mbggenerated
     */
    public String getSignOutLng2() {
        return signOutLng2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_lng2
     *
     * @param signOutLng2 the value for gzb01_t_user_sign_record.sign_out_lng2
     *
     * @mbggenerated
     */
    public void setSignOutLng2(String signOutLng2) {
        this.signOutLng2 = signOutLng2 == null ? null : signOutLng2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.strategy_id
     *
     * @return the value of gzb01_t_user_sign_record.strategy_id
     *
     * @mbggenerated
     */
    public Integer getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.strategy_id
     *
     * @param strategyId the value for gzb01_t_user_sign_record.strategy_id
     *
     * @mbggenerated
     */
    public void setStrategyId(Integer strategyId) {
        this.strategyId = strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_type1
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_type1
     *
     * @mbggenerated
     */
    public Byte getSignInType1() {
        return signInType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_type1
     *
     * @param signInType1 the value for gzb01_t_user_sign_record.sign_in_type1
     *
     * @mbggenerated
     */
    public void setSignInType1(Byte signInType1) {
        this.signInType1 = signInType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_type1
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_type1
     *
     * @mbggenerated
     */
    public Byte getSignOutType1() {
        return signOutType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_type1
     *
     * @param signOutType1 the value for gzb01_t_user_sign_record.sign_out_type1
     *
     * @mbggenerated
     */
    public void setSignOutType1(Byte signOutType1) {
        this.signOutType1 = signOutType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_in_type2
     *
     * @return the value of gzb01_t_user_sign_record.sign_in_type2
     *
     * @mbggenerated
     */
    public Byte getSignInType2() {
        return signInType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_in_type2
     *
     * @param signInType2 the value for gzb01_t_user_sign_record.sign_in_type2
     *
     * @mbggenerated
     */
    public void setSignInType2(Byte signInType2) {
        this.signInType2 = signInType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.sign_out_type2
     *
     * @return the value of gzb01_t_user_sign_record.sign_out_type2
     *
     * @mbggenerated
     */
    public Byte getSignOutType2() {
        return signOutType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.sign_out_type2
     *
     * @param signOutType2 the value for gzb01_t_user_sign_record.sign_out_type2
     *
     * @mbggenerated
     */
    public void setSignOutType2(Byte signOutType2) {
        this.signOutType2 = signOutType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.full_attendance
     *
     * @return the value of gzb01_t_user_sign_record.full_attendance
     *
     * @mbggenerated
     */
    public Byte getFullAttendance() {
        return fullAttendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.full_attendance
     *
     * @param fullAttendance the value for gzb01_t_user_sign_record.full_attendance
     *
     * @mbggenerated
     */
    public void setFullAttendance(Byte fullAttendance) {
        this.fullAttendance = fullAttendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.check_in
     *
     * @return the value of gzb01_t_user_sign_record.check_in
     *
     * @mbggenerated
     */
    public Byte getCheckIn() {
        return checkIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.check_in
     *
     * @param checkIn the value for gzb01_t_user_sign_record.check_in
     *
     * @mbggenerated
     */
    public void setCheckIn(Byte checkIn) {
        this.checkIn = checkIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_sign_record.is_available
     *
     * @return the value of gzb01_t_user_sign_record.is_available
     *
     * @mbggenerated
     */
    public Byte getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_sign_record.is_available
     *
     * @param isAvailable the value for gzb01_t_user_sign_record.is_available
     *
     * @mbggenerated
     */
    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }
}