package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_user_lack_attendance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.record_date
     *
     * @mbggenerated
     */
    private Date recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.lack_time1
     *
     * @mbggenerated
     */
    private Date lackTime1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.lack_time2
     *
     * @mbggenerated
     */
    private Date lackTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.record_type
     *
     * @mbggenerated
     */
    private Byte recordType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.strategy_id
     *
     * @mbggenerated
     */
    private Integer strategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_lack_attendance.is_available
     *
     * @mbggenerated
     */
    private Byte isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.id
     *
     * @return the value of gzb01_t_user_lack_attendance.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.id
     *
     * @param id the value for gzb01_t_user_lack_attendance.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.user_id
     *
     * @return the value of gzb01_t_user_lack_attendance.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.user_id
     *
     * @param userId the value for gzb01_t_user_lack_attendance.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.group_id
     *
     * @return the value of gzb01_t_user_lack_attendance.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.group_id
     *
     * @param groupId the value for gzb01_t_user_lack_attendance.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.project_id
     *
     * @return the value of gzb01_t_user_lack_attendance.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.project_id
     *
     * @param projectId the value for gzb01_t_user_lack_attendance.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.record_date
     *
     * @return the value of gzb01_t_user_lack_attendance.record_date
     *
     * @mbggenerated
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.record_date
     *
     * @param recordDate the value for gzb01_t_user_lack_attendance.record_date
     *
     * @mbggenerated
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.lack_time1
     *
     * @return the value of gzb01_t_user_lack_attendance.lack_time1
     *
     * @mbggenerated
     */
    public Date getLackTime1() {
        return lackTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.lack_time1
     *
     * @param lackTime1 the value for gzb01_t_user_lack_attendance.lack_time1
     *
     * @mbggenerated
     */
    public void setLackTime1(Date lackTime1) {
        this.lackTime1 = lackTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.lack_time2
     *
     * @return the value of gzb01_t_user_lack_attendance.lack_time2
     *
     * @mbggenerated
     */
    public Date getLackTime2() {
        return lackTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.lack_time2
     *
     * @param lackTime2 the value for gzb01_t_user_lack_attendance.lack_time2
     *
     * @mbggenerated
     */
    public void setLackTime2(Date lackTime2) {
        this.lackTime2 = lackTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.record_type
     *
     * @return the value of gzb01_t_user_lack_attendance.record_type
     *
     * @mbggenerated
     */
    public Byte getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.record_type
     *
     * @param recordType the value for gzb01_t_user_lack_attendance.record_type
     *
     * @mbggenerated
     */
    public void setRecordType(Byte recordType) {
        this.recordType = recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.strategy_id
     *
     * @return the value of gzb01_t_user_lack_attendance.strategy_id
     *
     * @mbggenerated
     */
    public Integer getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.strategy_id
     *
     * @param strategyId the value for gzb01_t_user_lack_attendance.strategy_id
     *
     * @mbggenerated
     */
    public void setStrategyId(Integer strategyId) {
        this.strategyId = strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_lack_attendance.is_available
     *
     * @return the value of gzb01_t_user_lack_attendance.is_available
     *
     * @mbggenerated
     */
    public Byte getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_lack_attendance.is_available
     *
     * @param isAvailable the value for gzb01_t_user_lack_attendance.is_available
     *
     * @mbggenerated
     */
    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }
}