package com.ttl.myspringboot.po;

public class gzb01_t_user_flow_role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_flow_role.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_flow_role.flow _id
     *
     * @mbggenerated
     */
    private Integer flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_flow_role.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_flow_role.user_id
     *
     * @return the value of gzb01_t_user_flow_role.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_flow_role.user_id
     *
     * @param userId the value for gzb01_t_user_flow_role.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_flow_role.flow _id
     *
     * @return the value of gzb01_t_user_flow_role.flow _id
     *
     * @mbggenerated
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_flow_role.flow _id
     *
     * @param flowId the value for gzb01_t_user_flow_role.flow _id
     *
     * @mbggenerated
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_flow_role.group_id
     *
     * @return the value of gzb01_t_user_flow_role.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_flow_role.group_id
     *
     * @param groupId the value for gzb01_t_user_flow_role.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}