package com.ttl.myspringboot.po;

public class gzb01_t_sign_strategy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_sign_strategy.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_sign_strategy.time_rule_id
     *
     * @mbggenerated
     */
    private Integer timeRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_sign_strategy.address_rule_list
     *
     * @mbggenerated
     */
    private String addressRuleList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_sign_strategy.is_available
     *
     * @mbggenerated
     */
    private Byte isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_sign_strategy.id
     *
     * @return the value of gzb01_t_sign_strategy.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_sign_strategy.id
     *
     * @param id the value for gzb01_t_sign_strategy.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_sign_strategy.time_rule_id
     *
     * @return the value of gzb01_t_sign_strategy.time_rule_id
     *
     * @mbggenerated
     */
    public Integer getTimeRuleId() {
        return timeRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_sign_strategy.time_rule_id
     *
     * @param timeRuleId the value for gzb01_t_sign_strategy.time_rule_id
     *
     * @mbggenerated
     */
    public void setTimeRuleId(Integer timeRuleId) {
        this.timeRuleId = timeRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_sign_strategy.address_rule_list
     *
     * @return the value of gzb01_t_sign_strategy.address_rule_list
     *
     * @mbggenerated
     */
    public String getAddressRuleList() {
        return addressRuleList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_sign_strategy.address_rule_list
     *
     * @param addressRuleList the value for gzb01_t_sign_strategy.address_rule_list
     *
     * @mbggenerated
     */
    public void setAddressRuleList(String addressRuleList) {
        this.addressRuleList = addressRuleList == null ? null : addressRuleList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_sign_strategy.is_available
     *
     * @return the value of gzb01_t_sign_strategy.is_available
     *
     * @mbggenerated
     */
    public Byte getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_sign_strategy.is_available
     *
     * @param isAvailable the value for gzb01_t_sign_strategy.is_available
     *
     * @mbggenerated
     */
    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }
}