package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_user {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.id_no
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.birth
     *
     * @mbggenerated
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.work_age
     *
     * @mbggenerated
     */
    private Integer workAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.height
     *
     * @mbggenerated
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.photo_url
     *
     * @mbggenerated
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.gzb_role_id
     *
     * @mbggenerated
     */
    private Integer gzbRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.district_id
     *
     * @mbggenerated
     */
    private Integer districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.live_id
     *
     * @mbggenerated
     */
    private Integer liveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.vocation_id
     *
     * @mbggenerated
     */
    private Integer vocationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.work_district_id
     *
     * @mbggenerated
     */
    private Integer workDistrictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.reg_district_id
     *
     * @mbggenerated
     */
    private Integer regDistrictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user.user_status
     *
     * @mbggenerated
     */
    private Byte userStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.id
     *
     * @return the value of gzb01_t_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.id
     *
     * @param id the value for gzb01_t_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.phone
     *
     * @return the value of gzb01_t_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.phone
     *
     * @param phone the value for gzb01_t_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.password
     *
     * @return the value of gzb01_t_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.password
     *
     * @param password the value for gzb01_t_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.user_name
     *
     * @return the value of gzb01_t_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.user_name
     *
     * @param userName the value for gzb01_t_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.id_no
     *
     * @return the value of gzb01_t_user.id_no
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.id_no
     *
     * @param idNo the value for gzb01_t_user.id_no
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.birth
     *
     * @return the value of gzb01_t_user.birth
     *
     * @mbggenerated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.birth
     *
     * @param birth the value for gzb01_t_user.birth
     *
     * @mbggenerated
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.sex
     *
     * @return the value of gzb01_t_user.sex
     *
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.sex
     *
     * @param sex the value for gzb01_t_user.sex
     *
     * @mbggenerated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.age
     *
     * @return the value of gzb01_t_user.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.age
     *
     * @param age the value for gzb01_t_user.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.work_age
     *
     * @return the value of gzb01_t_user.work_age
     *
     * @mbggenerated
     */
    public Integer getWorkAge() {
        return workAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.work_age
     *
     * @param workAge the value for gzb01_t_user.work_age
     *
     * @mbggenerated
     */
    public void setWorkAge(Integer workAge) {
        this.workAge = workAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.height
     *
     * @return the value of gzb01_t_user.height
     *
     * @mbggenerated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.height
     *
     * @param height the value for gzb01_t_user.height
     *
     * @mbggenerated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.weight
     *
     * @return the value of gzb01_t_user.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.weight
     *
     * @param weight the value for gzb01_t_user.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.photo_url
     *
     * @return the value of gzb01_t_user.photo_url
     *
     * @mbggenerated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.photo_url
     *
     * @param photoUrl the value for gzb01_t_user.photo_url
     *
     * @mbggenerated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.gzb_role_id
     *
     * @return the value of gzb01_t_user.gzb_role_id
     *
     * @mbggenerated
     */
    public Integer getGzbRoleId() {
        return gzbRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.gzb_role_id
     *
     * @param gzbRoleId the value for gzb01_t_user.gzb_role_id
     *
     * @mbggenerated
     */
    public void setGzbRoleId(Integer gzbRoleId) {
        this.gzbRoleId = gzbRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.district_id
     *
     * @return the value of gzb01_t_user.district_id
     *
     * @mbggenerated
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.district_id
     *
     * @param districtId the value for gzb01_t_user.district_id
     *
     * @mbggenerated
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.live_id
     *
     * @return the value of gzb01_t_user.live_id
     *
     * @mbggenerated
     */
    public Integer getLiveId() {
        return liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.live_id
     *
     * @param liveId the value for gzb01_t_user.live_id
     *
     * @mbggenerated
     */
    public void setLiveId(Integer liveId) {
        this.liveId = liveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.address
     *
     * @return the value of gzb01_t_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.address
     *
     * @param address the value for gzb01_t_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.vocation_id
     *
     * @return the value of gzb01_t_user.vocation_id
     *
     * @mbggenerated
     */
    public Integer getVocationId() {
        return vocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.vocation_id
     *
     * @param vocationId the value for gzb01_t_user.vocation_id
     *
     * @mbggenerated
     */
    public void setVocationId(Integer vocationId) {
        this.vocationId = vocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.work_district_id
     *
     * @return the value of gzb01_t_user.work_district_id
     *
     * @mbggenerated
     */
    public Integer getWorkDistrictId() {
        return workDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.work_district_id
     *
     * @param workDistrictId the value for gzb01_t_user.work_district_id
     *
     * @mbggenerated
     */
    public void setWorkDistrictId(Integer workDistrictId) {
        this.workDistrictId = workDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.reg_district_id
     *
     * @return the value of gzb01_t_user.reg_district_id
     *
     * @mbggenerated
     */
    public Integer getRegDistrictId() {
        return regDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.reg_district_id
     *
     * @param regDistrictId the value for gzb01_t_user.reg_district_id
     *
     * @mbggenerated
     */
    public void setRegDistrictId(Integer regDistrictId) {
        this.regDistrictId = regDistrictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.create_time
     *
     * @return the value of gzb01_t_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.create_time
     *
     * @param createTime the value for gzb01_t_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user.user_status
     *
     * @return the value of gzb01_t_user.user_status
     *
     * @mbggenerated
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user.user_status
     *
     * @param userStatus the value for gzb01_t_user.user_status
     *
     * @mbggenerated
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }
}