package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_task_rule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_rule.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_rule.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_rule.vocation_id
     *
     * @mbggenerated
     */
    private Integer vocationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_rule.vocation_name
     *
     * @mbggenerated
     */
    private String vocationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_rule.total_num
     *
     * @mbggenerated
     */
    private Integer totalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_rule.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_rule.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_rule.task_rule_status
     *
     * @mbggenerated
     */
    private Byte taskRuleStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_rule.id
     *
     * @return the value of gzb01_t_task_rule.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_rule.id
     *
     * @param id the value for gzb01_t_task_rule.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_rule.project_id
     *
     * @return the value of gzb01_t_task_rule.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_rule.project_id
     *
     * @param projectId the value for gzb01_t_task_rule.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_rule.vocation_id
     *
     * @return the value of gzb01_t_task_rule.vocation_id
     *
     * @mbggenerated
     */
    public Integer getVocationId() {
        return vocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_rule.vocation_id
     *
     * @param vocationId the value for gzb01_t_task_rule.vocation_id
     *
     * @mbggenerated
     */
    public void setVocationId(Integer vocationId) {
        this.vocationId = vocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_rule.vocation_name
     *
     * @return the value of gzb01_t_task_rule.vocation_name
     *
     * @mbggenerated
     */
    public String getVocationName() {
        return vocationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_rule.vocation_name
     *
     * @param vocationName the value for gzb01_t_task_rule.vocation_name
     *
     * @mbggenerated
     */
    public void setVocationName(String vocationName) {
        this.vocationName = vocationName == null ? null : vocationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_rule.total_num
     *
     * @return the value of gzb01_t_task_rule.total_num
     *
     * @mbggenerated
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_rule.total_num
     *
     * @param totalNum the value for gzb01_t_task_rule.total_num
     *
     * @mbggenerated
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_rule.start_date
     *
     * @return the value of gzb01_t_task_rule.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_rule.start_date
     *
     * @param startDate the value for gzb01_t_task_rule.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_rule.end_date
     *
     * @return the value of gzb01_t_task_rule.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_rule.end_date
     *
     * @param endDate the value for gzb01_t_task_rule.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_rule.task_rule_status
     *
     * @return the value of gzb01_t_task_rule.task_rule_status
     *
     * @mbggenerated
     */
    public Byte getTaskRuleStatus() {
        return taskRuleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_rule.task_rule_status
     *
     * @param taskRuleStatus the value for gzb01_t_task_rule.task_rule_status
     *
     * @mbggenerated
     */
    public void setTaskRuleStatus(Byte taskRuleStatus) {
        this.taskRuleStatus = taskRuleStatus;
    }
}