package com.ttl.myspringboot.po;

public class gzb01_t_project_member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_member.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_member.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_member.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_member.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_member.user_status
     *
     * @mbggenerated
     */
    private Byte userStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_member.id
     *
     * @return the value of gzb01_t_project_member.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_member.id
     *
     * @param id the value for gzb01_t_project_member.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_member.project_id
     *
     * @return the value of gzb01_t_project_member.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_member.project_id
     *
     * @param projectId the value for gzb01_t_project_member.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_member.user_id
     *
     * @return the value of gzb01_t_project_member.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_member.user_id
     *
     * @param userId the value for gzb01_t_project_member.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_member.role_id
     *
     * @return the value of gzb01_t_project_member.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_member.role_id
     *
     * @param roleId the value for gzb01_t_project_member.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_member.user_status
     *
     * @return the value of gzb01_t_project_member.user_status
     *
     * @mbggenerated
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_member.user_status
     *
     * @param userStatus the value for gzb01_t_project_member.user_status
     *
     * @mbggenerated
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }
}