package com.ttl.myspringboot.po;

public class gzb01_t_user_company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_company.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_company.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_user_company.rel_status
     *
     * @mbggenerated
     */
    private Byte relStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_company.user_id
     *
     * @return the value of gzb01_t_user_company.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_company.user_id
     *
     * @param userId the value for gzb01_t_user_company.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_company.company_id
     *
     * @return the value of gzb01_t_user_company.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_company.company_id
     *
     * @param companyId the value for gzb01_t_user_company.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_user_company.rel_status
     *
     * @return the value of gzb01_t_user_company.rel_status
     *
     * @mbggenerated
     */
    public Byte getRelStatus() {
        return relStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_user_company.rel_status
     *
     * @param relStatus the value for gzb01_t_user_company.rel_status
     *
     * @mbggenerated
     */
    public void setRelStatus(Byte relStatus) {
        this.relStatus = relStatus;
    }
}