package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_project_group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_group.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_group.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_group.project_id
     *
     * @mbggenerated
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_group.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_group.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_group.eval_level
     *
     * @mbggenerated
     */
    private Byte evalLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_project_group.rel_status
     *
     * @mbggenerated
     */
    private Byte relStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_group.id
     *
     * @return the value of gzb01_t_project_group.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_group.id
     *
     * @param id the value for gzb01_t_project_group.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_group.group_id
     *
     * @return the value of gzb01_t_project_group.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_group.group_id
     *
     * @param groupId the value for gzb01_t_project_group.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_group.project_id
     *
     * @return the value of gzb01_t_project_group.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_group.project_id
     *
     * @param projectId the value for gzb01_t_project_group.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_group.start_date
     *
     * @return the value of gzb01_t_project_group.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_group.start_date
     *
     * @param startDate the value for gzb01_t_project_group.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_group.end_date
     *
     * @return the value of gzb01_t_project_group.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_group.end_date
     *
     * @param endDate the value for gzb01_t_project_group.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_group.eval_level
     *
     * @return the value of gzb01_t_project_group.eval_level
     *
     * @mbggenerated
     */
    public Byte getEvalLevel() {
        return evalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_group.eval_level
     *
     * @param evalLevel the value for gzb01_t_project_group.eval_level
     *
     * @mbggenerated
     */
    public void setEvalLevel(Byte evalLevel) {
        this.evalLevel = evalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_project_group.rel_status
     *
     * @return the value of gzb01_t_project_group.rel_status
     *
     * @mbggenerated
     */
    public Byte getRelStatus() {
        return relStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_project_group.rel_status
     *
     * @param relStatus the value for gzb01_t_project_group.rel_status
     *
     * @mbggenerated
     */
    public void setRelStatus(Byte relStatus) {
        this.relStatus = relStatus;
    }
}