package com.ttl.myspringboot.po;

public class gzb01_t_task_group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_group.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_group.task_rule_id
     *
     * @mbggenerated
     */
    private Integer taskRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_group.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_task_group.rel_status
     *
     * @mbggenerated
     */
    private Byte relStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_group.id
     *
     * @return the value of gzb01_t_task_group.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_group.id
     *
     * @param id the value for gzb01_t_task_group.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_group.task_rule_id
     *
     * @return the value of gzb01_t_task_group.task_rule_id
     *
     * @mbggenerated
     */
    public Integer getTaskRuleId() {
        return taskRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_group.task_rule_id
     *
     * @param taskRuleId the value for gzb01_t_task_group.task_rule_id
     *
     * @mbggenerated
     */
    public void setTaskRuleId(Integer taskRuleId) {
        this.taskRuleId = taskRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_group.group_id
     *
     * @return the value of gzb01_t_task_group.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_group.group_id
     *
     * @param groupId the value for gzb01_t_task_group.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_task_group.rel_status
     *
     * @return the value of gzb01_t_task_group.rel_status
     *
     * @mbggenerated
     */
    public Byte getRelStatus() {
        return relStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_task_group.rel_status
     *
     * @param relStatus the value for gzb01_t_task_group.rel_status
     *
     * @mbggenerated
     */
    public void setRelStatus(Byte relStatus) {
        this.relStatus = relStatus;
    }
}