package com.ttl.myspringboot.po;

public class gzb01_t_phone_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_phone_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_phone_info.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_phone_info.phone_model
     *
     * @mbggenerated
     */
    private String phoneModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_phone_info.app_version
     *
     * @mbggenerated
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_phone_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_phone_info.id
     *
     * @return the value of gzb01_t_phone_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_phone_info.id
     *
     * @param id the value for gzb01_t_phone_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_phone_info.device_id
     *
     * @return the value of gzb01_t_phone_info.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_phone_info.device_id
     *
     * @param deviceId the value for gzb01_t_phone_info.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_phone_info.phone_model
     *
     * @return the value of gzb01_t_phone_info.phone_model
     *
     * @mbggenerated
     */
    public String getPhoneModel() {
        return phoneModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_phone_info.phone_model
     *
     * @param phoneModel the value for gzb01_t_phone_info.phone_model
     *
     * @mbggenerated
     */
    public void setPhoneModel(String phoneModel) {
        this.phoneModel = phoneModel == null ? null : phoneModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_phone_info.app_version
     *
     * @return the value of gzb01_t_phone_info.app_version
     *
     * @mbggenerated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_phone_info.app_version
     *
     * @param appVersion the value for gzb01_t_phone_info.app_version
     *
     * @mbggenerated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_phone_info.phone
     *
     * @return the value of gzb01_t_phone_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_phone_info.phone
     *
     * @param phone the value for gzb01_t_phone_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}