package com.ttl.myspringboot.po;

import java.util.Date;

public class gzb01_t_location_favorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_location_favorite.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_location_favorite.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_location_favorite.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_location_favorite.lng
     *
     * @mbggenerated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_location_favorite.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_location_favorite.favorite_type
     *
     * @mbggenerated
     */
    private Byte favoriteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_location_favorite.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_location_favorite.is_available
     *
     * @mbggenerated
     */
    private Byte isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_location_favorite.id
     *
     * @return the value of gzb01_t_location_favorite.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_location_favorite.id
     *
     * @param id the value for gzb01_t_location_favorite.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_location_favorite.user_id
     *
     * @return the value of gzb01_t_location_favorite.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_location_favorite.user_id
     *
     * @param userId the value for gzb01_t_location_favorite.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_location_favorite.lat
     *
     * @return the value of gzb01_t_location_favorite.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_location_favorite.lat
     *
     * @param lat the value for gzb01_t_location_favorite.lat
     *
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_location_favorite.lng
     *
     * @return the value of gzb01_t_location_favorite.lng
     *
     * @mbggenerated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_location_favorite.lng
     *
     * @param lng the value for gzb01_t_location_favorite.lng
     *
     * @mbggenerated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_location_favorite.address
     *
     * @return the value of gzb01_t_location_favorite.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_location_favorite.address
     *
     * @param address the value for gzb01_t_location_favorite.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_location_favorite.favorite_type
     *
     * @return the value of gzb01_t_location_favorite.favorite_type
     *
     * @mbggenerated
     */
    public Byte getFavoriteType() {
        return favoriteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_location_favorite.favorite_type
     *
     * @param favoriteType the value for gzb01_t_location_favorite.favorite_type
     *
     * @mbggenerated
     */
    public void setFavoriteType(Byte favoriteType) {
        this.favoriteType = favoriteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_location_favorite.create_time
     *
     * @return the value of gzb01_t_location_favorite.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_location_favorite.create_time
     *
     * @param createTime the value for gzb01_t_location_favorite.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_location_favorite.is_available
     *
     * @return the value of gzb01_t_location_favorite.is_available
     *
     * @mbggenerated
     */
    public Byte getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_location_favorite.is_available
     *
     * @param isAvailable the value for gzb01_t_location_favorite.is_available
     *
     * @mbggenerated
     */
    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }
}