package com.ttl.myspringboot.po;

public class gzb01_t_register {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_register.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_register.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gzb01_t_register.register_status
     *
     * @mbggenerated
     */
    private Byte registerStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_register.id
     *
     * @return the value of gzb01_t_register.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_register.id
     *
     * @param id the value for gzb01_t_register.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_register.phone
     *
     * @return the value of gzb01_t_register.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_register.phone
     *
     * @param phone the value for gzb01_t_register.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gzb01_t_register.register_status
     *
     * @return the value of gzb01_t_register.register_status
     *
     * @mbggenerated
     */
    public Byte getRegisterStatus() {
        return registerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gzb01_t_register.register_status
     *
     * @param registerStatus the value for gzb01_t_register.register_status
     *
     * @mbggenerated
     */
    public void setRegisterStatus(Byte registerStatus) {
        this.registerStatus = registerStatus;
    }
}